%YAML:1.0
---
model_type: KANNALA_BRANDT
camera_name: camera
image_width: 640
image_height: 480
projection_parameters:
   # k2: 0.0034823894022493434
   # k3: 0.0007150348452162257
   # k4: -0.0020532361418706202
   # k5: 0.00020293673591811182
   k2: -6.545154718304953e-06
   k3: -0.010379525898159981
   k4: 0.014935312423953146
   k5: -0.005639061406567785
   mu: 275.46015578667294
   mv: 274.9948095922592
   u0: 315.958384100568
   v0: 242.7123497822731


#### for pose graph node 
image_topic: "/snappy_cam/stereo_l"
output_path: "/home/davidz/work/result/fpv_forward_45"
#loop closure parameters
loop_closure: 1 #1                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 1             # useful in real-time and large project
pose_graph_save_path: "/home/davidz/work/result/pose_graph/" # save and load path

#visualization parameters
save_image: 1 #1                   # save image in pose graph for visualization prupose; you can close this function by setting 0
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ

