%YAML:1.0
---
model_type: KANNALA_BRANDT
camera_name: camera
image_width: 640
image_height: 480
projection_parameters:
   k2: -0.005719912631104124
   k3: 0.004742449009601135
   k4: 0.0012060658036136048
   k5: -0.001580292679344826
   mu: 277.4786896484645 
   mv: 277.42548548840034
   u0: 320.1052053576385 
   v0: 242.10083077857894


#### for pose graph node 
image_topic: "/snappy_cam/stereo_l"
output_path: "/home/davidz/work/result/fpv_out_forward"
#loop closure parameters
loop_closure: 1 #1                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 1             # useful in real-time and large project
pose_graph_save_path: "/home/davidz/work/result/pose_graph/" # save and load path

#visualization parameters
save_image: 1 #1                   # save image in pose graph for visualization prupose; you can close this function by setting 0
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ

